### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
@backend_HostAddress = http://localhost:8080
###

PUT http://localhost:8080/api/products/updateProduct3
Content-Type: application/json

{
  "id": 1,
  "name": "almond",
  "items": "test",
  "pricePerUnit": "30",
  "totalPrice": "60"
}

###
POST {{backend_HostAddress}}/api/products/deleteProduct/3

###
POST http://localhost:8080/api/inventory/addNewInventory
Content-Type: application/json

{
  "id": 1,
  "name": "almond",
  "items": "test",
  "pricePerUnit": "30",
  "totalPrice": "60",
  "type": "raw_material"
}