### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
@backend_HostAddress = http://localhost:8080
###

PUT http://localhost:8080/api/products/updateProduct3
Content-Type: application/json

{
  "id": 1,
  "name": "almond",
  "items": "test",
  "pricePerUnit": "30",
  "totalPrice": "60"
}
###
GET {{backend_HostAddress}}//api/orders

###
POST {{backend_HostAddress}}/api/products/deleteProduct/3

###
POST {{backend_HostAddress}}//api/orders/getAllOrders

###
POST {{backend_HostAddress}}/api/products/addNewProduct
Content-Type: application/json

{
  "id": 1,
  "name": "almond",
  "items": "test",
  "type": "raw_material",
  "pricePerUnit": "30",
  "totalPrice": "60"
}
###
POST http://localhost:8080/api/inventory/addNewInventory
Content-Type: application/json

{
  "quantity": 10,
  "pricePerUnit": 20,
  "totalPrice": 300.0,
  "totalAmount": 300.0,
  "product": {
    "id": 1
  },
  "user": {
    "id": 1
  }
}
###
DELETE {{backend_HostAddress}}/api/inventory/deleteInventory/2
